services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./alembic/versions:/app/alembic/versions
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - API_GAMES=${API_GAMES}
      - API_IMAGE=${API_IMAGE}
      - API=${API}
      - LLM_KEY=${LLM_KEY}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
      - SYNC_KEY=${SYNC_KEY}
      - AWS_REGION=${AWS_REGION}
      - SQS_QUEUE=${SQS_QUEUE}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      db:
        condition: service_healthy
      elasticmq:
        condition: service_started

  worker:
    build: .
    command: /app/.venv/bin/python workers/processor.py
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - API=${API}
      - LLM_KEY=${LLM_KEY}
      - SYNC_KEY=${SYNC_KEY}
      - AWS_REGION=${AWS_REGION}
      - SQS_QUEUE=${SQS_QUEUE}
      - SQS_ENDPOINT=${SQS_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      db:
        condition: service_healthy
      elasticmq:
        condition: service_started

  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

volumes:
  postgres_data:
