[pytest]
pythonpath = .

env =
    DB_HOST=test
    DB_PASSWORD=test
    DB_NAME=test
    DB_USER=test
    API_GAMES=test
    API_IMAGE=test
    LLM_KEY=test
    SYSTEM_PROMPT=test
    SYNC_KEY=test
    AWS_REGION=test
    SQS_QUEUE=test
    SQS_ENDPOINT=test
    S3_BUCKET=test
