name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install JavaScript dependencies
        run: pnpm install

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync --frozen
        working-directory: ./apps/api

      - name: Run tasks
        env:
          API: ${{ secrets.API }}
          GAMES_PAGE_1: ${{ secrets.GAMES_PAGE_1 }}
          GAMES_PAGE_2: ${{ secrets.GAMES_PAGE_2 }}
          QUERIES: ${{ secrets.QUERIES }}
          IMAGES: ${{ secrets.IMAGES }}
        run: pnpm turbo run build lint test
